# config/packages/security.yaml

security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
      # Le JWT gérera automatiquement l'authentification
      # Les routes publiques sont gérées par access_control

    main:
      lazy: true
      provider: app_user_provider
      # Ajoutez ici vos méthodes d'authentification pour l'interface web
      # form_login:
      #   login_path: login
      #   check_path: login

  access_control:
    - { path: ^/api/login$, roles: PUBLIC_ACCESS }
    - { path: ^/api/register$, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }